'use client';
import {useState,useTransition,useEffect} from 'react';
import {useRouter} from 'next/navigation';
import type {Child,Session} from '@/lib/data/tracker';
import {displayMinutes} from '@/lib/session-time';
import {manageRecord} from '@/lib/actions/manage';
const local=(iso:string)=>{const d=new Date(iso);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);};
export default function Management({children,sessions}:{children:Child[];sessions:Session[]}){
 const router=useRouter();const [editing,setEditing]=useState<Child|null>(null),[session,setSession]=useState<Session|null>(null),[adding,setAdding]=useState(false),[filter,setFilter]=useState(''),[date,setDate]=useState(''),[removing,setRemoving]=useState<{entity:string;id:string;name:string}|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[pending,begin]=useTransition();
 useEffect(()=>{if(adding||editing||session||removing){const panel=document.querySelector('[data-active-form]');panel?.scrollIntoView({behavior:'smooth',block:'start'});panel?.querySelector<HTMLInputElement>('input:not([type=hidden]),select')?.focus({preventScroll:true});}},[adding,editing,session,removing]);
 const save=(form:FormData)=>{setError('');setMessage('');if(form.get('started_at'))form.set('started_at',new Date(String(form.get('started_at'))).toISOString());begin(async()=>{const result=await manageRecord(form);if(result.error)setError(result.error);else{setMessage(result.success!);setEditing(null);setAdding(false);setSession(null);setRemoving(null);router.refresh();}});};
 return <>{message&&<p className="notice" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}<section><div className="section-title"><h2>Children in your care</h2><button className="button" onClick={()=>{setAdding(true);setEditing(null);setError('');}}>+ Add child</button></div>{children.length===0&&<p className="empty">Add your first child to start tracking.</p>}<div className="cards">{children.map(c=><article className="child-card" key={c.id}><h3>{c.name}</h3><p className="muted">{c.age!==null?`Age ${c.age} · `:''}{c.daily_limit_minutes} min/day</p>{c.notes&&<p>{c.notes}</p>}<div className="row-actions"><button onClick={()=>{setEditing(c);setAdding(false);setError('');}}>Edit child & limit</button><button onClick={()=>setRemoving({entity:'child',id:c.id,name:c.name})}>Remove child</button><button onClick={()=>setFilter(c.id)}>View history</button></div></article>)}</div></section>
 {(adding||editing)&&<section className="form-panel" data-active-form><h2>{editing?'Edit child & daily limit':'Add a child'}</h2><form key={editing?.id||'new'} action={save}><input type="hidden" name="entity" value="child"/><input type="hidden" name="operation" value={editing?'update':'create'}/><input type="hidden" name="id" value={editing?.id||''}/><label>Name<input name="name" required maxLength={80} defaultValue={editing?.name}/></label><div className="form-grid"><label>Age (optional)<input name="age" type="number" min="0" max="18" defaultValue={editing?.age??''}/></label><label>Daily limit (minutes)<input name="daily_limit_minutes" type="number" min="1" max="1440" required defaultValue={editing?.daily_limit_minutes??120}/></label></div><label>Notes (optional)<textarea name="notes" maxLength={2000} defaultValue={editing?.notes||''}/></label>{editing&&<label>Reason for change<input name="reason" required minLength={3} maxLength={500}/></label>}<button className="button" disabled={pending}>{pending?'Saving…':'Save child'}</button> <button type="button" onClick={()=>{setAdding(false);setEditing(null);}}>Cancel</button></form></section>}
 <section><h2>Session history</h2><div className="form-grid"><label>Child<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All children</option>{children.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Day (optional)<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className="history">{sessions.filter(s=>(!filter||s.child_id===filter)&&(!date||local(s.started_at).slice(0,10)===date)).map(s=><div className="session-row" key={s.id}><div><strong>{children.find(c=>c.id===s.child_id)?.name} · {s.ended_at?displayMinutes((new Date(s.ended_at).getTime()-new Date(s.started_at).getTime())/60000)+' min':'Currently logged in'}</strong><p className="muted">{new Date(s.started_at).toLocaleString()} · {s.device_type} · {s.activity_type}</p>{s.notes&&<p>{s.notes}</p>}</div><div className="row-actions">{s.ended_at?<button onClick={()=>{setSession(s);setError('');}}>Edit session</button>:<a href="/">Log out on dashboard</a>}<button onClick={()=>setRemoving({entity:'screen_session',id:s.id,name:'this session'})}>Delete session</button></div></div>)}{!sessions.some(s=>(!filter||s.child_id===filter)&&(!date||local(s.started_at).slice(0,10)===date))&&<p className="muted">No sessions for this selection.</p>}</div></section>
 {session&&<section className="form-panel" data-active-form><h2>Edit session</h2><form key={session.id} action={save}><input type="hidden" name="entity" value="screen_session"/><input type="hidden" name="operation" value="update"/><input type="hidden" name="id" value={session.id}/><label>Child<select name="child_id" defaultValue={session.child_id}>{children.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="form-grid"><label>Device<select name="device_type" defaultValue={session.device_type}>{['tablet','tv','phone','computer','game-console'].map(v=><option key={v}>{v}</option>)}</select></label><label>Activity<select name="activity_type" defaultValue={session.activity_type}>{['educational','video','game','social','browsing'].map(v=><option key={v}>{v}</option>)}</select></label><label>Start time<input name="started_at" type="datetime-local" required defaultValue={local(session.started_at)}/></label><label>Duration (minutes)<input name="duration_minutes" type="number" required min="1" max="1440" defaultValue={session.duration_minutes}/></label></div><label>Note<textarea name="notes" maxLength={2000} defaultValue={session.notes||''}/></label><label>Reason for change<input name="reason" required minLength={3} maxLength={500}/></label><button className="button" disabled={pending}>{pending?'Saving…':'Save changes'}</button> <button type="button" onClick={()=>setSession(null)}>Cancel</button></form></section>}
 {removing&&<section className="form-panel" data-active-form role="dialog" aria-modal="false" aria-label="Confirm removal"><h2>Remove {removing.name}?</h2><p>{removing.entity==='child'?'This also removes this child’s sessions.':'This changes the daily total.'} This cannot be undone. An audit record will remain.</p><form action={save}><input type="hidden" name="entity" value={removing.entity}/><input type="hidden" name="operation" value="delete"/><input type="hidden" name="id" value={removing.id}/><label>Reason for removal<input name="reason" required minLength={3} maxLength={500}/></label><button className="button" disabled={pending}>{pending?'Removing…':'Confirm removal'}</button> <button type="button" onClick={()=>setRemoving(null)}>Cancel</button></form></section>}
 </>;
}

