'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState,useEffect,useTransition } from 'react';
import type {Child,Session} from '@/lib/data/tracker';
import Management from './management';
import TimerControls from './timer-controls';
import LimitNotifications from './limit-notifications';
import {minutesForDay,displayMinutes} from '@/lib/session-time';
import { logSession } from '@/lib/actions/tracker';
const dayOf=(date:string)=>new Date(date).toLocaleDateString('en-CA');
const localStart=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);};
export default function Tracker({children,sessions,view='dashboard'}:{children:Child[];sessions:Session[];view?:string}){
 const router=useRouter();const [today,setToday]=useState(''),[start,setStart]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[pending,begin]=useTransition(),[selectedChild,setSelectedChild]=useState(''),[now,setNow]=useState(0);
 useEffect(()=>{if(new URLSearchParams(window.location.search).has('saved'))setMessage('Session saved. Today’s totals are updated.');setNow(Date.now());setToday(dayOf(new Date().toISOString()));setStart(localStart());setSelectedChild(new URLSearchParams(window.location.search).get('child')||children[0]?.id||'');},[]);
 useEffect(()=>{if(view!=='dashboard')return;const timer=setInterval(()=>{setToday(dayOf(new Date().toISOString()));router.refresh();},30000);return ()=>clearInterval(timer);},[view,router]);
 useEffect(()=>{const clock=setInterval(()=>{setNow(Date.now());setToday(dayOf(new Date().toISOString()));},1000);return ()=>clearInterval(clock);},[]);
 const totals=new Map(children.map(c=>[c.id,sessions.filter(s=>s.child_id===c.id).reduce((n,s)=>n+minutesForDay(s,new Date(now),now),0)]));
 const ranked=[...children].sort((a,b)=>totals.get(b.id)!/b.daily_limit_minutes-totals.get(a.id)!/a.daily_limit_minutes);
 const navigation=<><Link aria-current={view==='dashboard'?'page':undefined} href="/">Today’s dashboard</Link><Link aria-current={view==='sessions'?'page':undefined} href="/sessions">Log session</Link><Link aria-current={view==='children'?'page':undefined} href="/children">Children & limits</Link></>;
 if(view==='dashboard'&&!now)return <main className="loading" aria-busy="true"><h1>Loading today's screen time…</h1><div className="skeleton"/></main>;
 return <div className="shell"><aside><Link className="brand" href="/">◷ <span>Screen Time<small>A little balance, every day</small></span></Link><details className="mobile-menu"><summary>Menu</summary><nav>{navigation}</nav></details><nav className="desktop-nav">{navigation}</nav><p className="demo-note">Shared demo workspace<br/>Use fictional children while exploring.</p></aside><main><header><div><p className="eyebrow">CAREGIVER WORKSPACE</p><h1>{view==='sessions'?'Log a screen session':view==='children'?'Children & daily limits':'A balanced day starts here.'}</h1><p className="muted">One daily allowance across every login and logout. Breaks do not count.</p></div><Link className="button" href="/sessions">+ Log session</Link></header>{message&&<p className="notice" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}
 <LimitNotifications children={children} totals={totals} running={new Set(sessions.filter(s=>!s.ended_at).map(s=>s.child_id))}/>{view==='dashboard'&&<><div className="stats"><div><span>Children in your care</span><strong>{children.length}</strong></div><div><span>Screen time today</span><strong>{displayMinutes([...totals.values()].reduce((a,b)=>a+b,0))} <small>min</small></strong></div><div><span>Reached their daily limit</span><strong>{children.filter(c=>totals.get(c.id)!>=c.daily_limit_minutes).length}</strong></div></div><section><div className="section-title"><h2>Today’s overview</h2><span className="muted">{today||'Loading local date…'}</span></div><p className="legend"><span>● Within limit</span><span>● Approaching (75–99%)</span><span>● Limit reached</span></p>{!children.length?<div className="empty"><h2>A fresh start</h2><p>Add a child to start tracking their day.</p><Link className="button" href="/children">Add a child</Link></div>:<div className="cards">{ranked.map(c=>{const total=totals.get(c.id)!,ratio=total/c.daily_limit_minutes,status=ratio>=1?'red':ratio>=.75?'amber':'green';return <article className="child-card" id={`child-${c.id}`} key={c.id}><div className="card-top"><span className="avatar">{c.name.slice(0,1)}</span><div><h3>{c.name}</h3><p className="muted">{c.age===null?'Age not set':`${c.age} years old`}</p></div><span className={`badge ${status}`}>{ratio>1?'Over limit':ratio===1?'Limit reached':ratio>=.75?'Approaching limit':'Looking balanced'}</span></div><p className="usage"><strong>{displayMinutes(total)}</strong> / {c.daily_limit_minutes} min</p><div className="bar" role="progressbar" aria-label={`${c.name} screen time`} aria-valuenow={total} aria-valuemin={0} aria-valuemax={Math.max(total,c.daily_limit_minutes)}><div className={status} style={{width:`${Math.min(100,ratio*100)}%`}}/></div><p className="muted">{total>c.daily_limit_minutes?`${displayMinutes(total-c.daily_limit_minutes)} minutes over the daily limit`:`${displayMinutes(c.daily_limit_minutes-total)} minutes remaining`}</p><TimerControls childId={c.id} active={sessions.find(s=>s.child_id===c.id&&!s.ended_at)}/><Link href={`/sessions?child=${c.id}`}>Log time for {c.name.split(' ')[0]} →</Link></article>;})}</div>}</section><section><h2>Today’s sessions</h2><div className="history">{sessions.filter(s=>minutesForDay(s,new Date(now),now)>0).map(s=><div className="session-row" key={s.id}><div><strong>{children.find(c=>c.id===s.child_id)?.name}</strong><p className="muted">{s.activity_type} · {s.device_type} · {new Date(s.started_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</p>{s.notes&&<p>{s.notes}</p>}</div><strong>{displayMinutes(minutesForDay(s,new Date(now),now))} min today{s.ended_at?'':' · running'}</strong></div>)}{!sessions.some(s=>minutesForDay(s,new Date(now),now)>0)&&<p className="muted">No sessions logged today.</p>}</div></section></>}
 {view==='sessions'&&<section className="form-panel"><h2>Record a moment</h2><p className="muted">Totals follow your browser’s local day.</p>{!children.length?<p>Add a child first in <Link href="/children">Children & limits</Link>.</p>:<form action={form=>{form.set('started_at',new Date(String(form.get('started_at'))).toISOString());setError('');begin(async()=>{const result=await logSession(form);if(result.error)setError(result.error);else{router.push('/?saved=1');router.refresh();}});}}><label>Child<select name="child_id" required value={selectedChild} onChange={e=>setSelectedChild(e.target.value)}>{children.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="form-grid"><label>Device<select name="device_type" defaultValue="tablet"><option value="tablet">Tablet</option><option value="tv">TV</option><option value="phone">Phone</option><option value="computer">Computer</option><option value="game-console">Game console</option></select></label><label>Activity<select name="activity_type" defaultValue="educational"><option value="educational">Educational</option><option value="video">Video</option><option value="game">Game</option><option value="social">Social</option><option value="browsing">Browsing</option></select></label><label>Start time<input name="started_at" type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Duration (minutes)<input name="duration_minutes" type="number" min="1" max="1440" required defaultValue="30"/></label></div><label>Note (optional)<textarea name="notes" maxLength={2000} placeholder="What were they watching or learning?"/></label><button disabled={pending} className="button">{pending?'Saving…':'Save session'}</button> <Link href="/">View today’s dashboard →</Link></form>}</section>}
 {view==='children'&&<Management children={children} sessions={sessions}/>} 
 <footer>Screen Time Control · Logged moments, clearer days.</footer></main></div>;
}


