'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState,useEffect,useTransition } from 'react';
import type {Child,Session} from '@/lib/data/tracker';
import { logSession } from '@/lib/actions/tracker';
const dayOf=(date:string)=>new Date(date).toLocaleDateString('en-CA');
const localStart=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);};
export default function Tracker({children,sessions,view='dashboard'}:{children:Child[];sessions:Session[];view?:string}){
 const router=useRouter();const [today,setToday]=useState(''),[start,setStart]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[pending,begin]=useTransition();
 useEffect(()=>{setToday(dayOf(new Date().toISOString()));setStart(localStart());},[]);
 const totals=new Map(children.map(c=>[c.id,sessions.filter(s=>s.child_id===c.id&&dayOf(s.started_at)===today).reduce((n,s)=>n+s.duration_minutes,0)]));
 const ranked=[...children].sort((a,b)=>totals.get(b.id)!/b.daily_limit_minutes-totals.get(a.id)!/a.daily_limit_minutes);
 const navigation=<><Link aria-current={view==='dashboard'?'page':undefined} href="/">Today’s dashboard</Link><Link aria-current={view==='sessions'?'page':undefined} href="/sessions">Log session</Link><Link aria-current={view==='children'?'page':undefined} href="/children">Children & limits</Link></>;
 return <div className="shell"><aside><Link className="brand" href="/">◷ <span>Screen Time<small>A little balance, every day</small></span></Link><details className="mobile-menu"><summary>Menu</summary><nav>{navigation}</nav></details><nav className="desktop-nav">{navigation}</nav><p className="demo-note">Shared demo workspace<br/>Use fictional children while exploring.</p></aside><main><header><div><p className="eyebrow">CAREGIVER WORKSPACE</p><h1>{view==='sessions'?'Log a screen session':view==='children'?'Children & daily limits':'A balanced day starts here.'}</h1><p className="muted">Keep an eye on screen time, one child at a time.</p></div><Link className="button" href="/sessions">+ Log session</Link></header>{message&&<p className="notice" role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}
 {view==='dashboard'&&<><div className="stats"><div><span>Children in your care</span><strong>{children.length}</strong></div><div><span>Screen time today</span><strong>{[...totals.values()].reduce((a,b)=>a+b,0)} <small>min</small></strong></div><div><span>Over their daily limit</span><strong>{children.filter(c=>totals.get(c.id)!>c.daily_limit_minutes).length}</strong></div></div><section><div className="section-title"><h2>Today’s overview</h2><span className="muted">{today||'Loading local date…'}</span></div><p className="legend"><span>● Within limit</span><span>● Approaching (75–100%)</span><span>● Over limit</span></p>{!children.length?<div className="empty"><h2>A fresh start</h2><p>Add a child to start tracking their day.</p><Link className="button" href="/children">Add a child</Link></div>:<div className="cards">{ranked.map(c=>{const total=totals.get(c.id)!,ratio=total/c.daily_limit_minutes,status=ratio>1?'red':ratio>=.75?'amber':'green';return <article className="child-card" key={c.id}><div className="card-top"><span className="avatar">{c.name.slice(0,1)}</span><div><h3>{c.name}</h3><p className="muted">{c.age===null?'Age not set':`${c.age} years old`}</p></div><span className={`badge ${status}`}>{ratio>1?'Over limit':ratio>=.75?'Approaching limit':'Looking balanced'}</span></div><p className="usage"><strong>{total}</strong> / {c.daily_limit_minutes} min</p><div className="bar" role="progressbar" aria-label={`${c.name} screen time`} aria-valuenow={total} aria-valuemin={0} aria-valuemax={Math.max(total,c.daily_limit_minutes)}><div className={status} style={{width:`${Math.min(100,ratio*100)}%`}}/></div><p className="muted">{total>c.daily_limit_minutes?`${total-c.daily_limit_minutes} minutes over the daily limit`:`${c.daily_limit_minutes-total} minutes remaining`}</p><Link href={`/sessions?child=${c.id}`}>Log time for {c.name.split(' ')[0]} →</Link></article>;})}</div>}</section><section><h2>Today’s sessions</h2><div className="history">{sessions.filter(s=>dayOf(s.started_at)===today).map(s=><div className="session-row" key={s.id}><div><strong>{children.find(c=>c.id===s.child_id)?.name}</strong><p className="muted">{s.activity_type} · {s.device_type} · {new Date(s.started_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</p>{s.notes&&<p>{s.notes}</p>}</div><strong>{s.duration_minutes} min</strong></div>)}{!sessions.some(s=>dayOf(s.started_at)===today)&&<p className="muted">No sessions logged today.</p>}</div></section></>}
 {view==='sessions'&&<section className="form-panel"><h2>Record a moment</h2><p className="muted">Totals follow your browser’s local day.</p>{!children.length?<p>Add a child first in <Link href="/children">Children & limits</Link>.</p>:<form action={form=>{form.set('started_at',new Date(String(form.get('started_at'))).toISOString());setError('');begin(async()=>{const result=await logSession(form);if(result.error)setError(result.error);else{setMessage(result.success!);router.refresh();}});}}><label>Child<select name="child_id" required>{children.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="form-grid"><label>Device<select name="device_type" defaultValue="tablet"><option value="tablet">Tablet</option><option value="tv">TV</option><option value="phone">Phone</option><option value="computer">Computer</option><option value="game-console">Game console</option></select></label><label>Activity<select name="activity_type" defaultValue="educational"><option value="educational">Educational</option><option value="video">Video</option><option value="game">Game</option><option value="social">Social</option><option value="browsing">Browsing</option></select></label><label>Start time<input name="started_at" type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Duration (minutes)<input name="duration_minutes" type="number" min="1" max="1440" required defaultValue="30"/></label></div><label>Note (optional)<textarea name="notes" maxLength={2000} placeholder="What were they watching or learning?"/></label><button disabled={pending} className="button">{pending?'Saving…':'Save session'}</button> <Link href="/">View today’s dashboard →</Link></form>}</section>}
 {view==='children'&&<section><h2>Children in your care</h2>{children.map(c=><p key={c.id}>{c.name} · {c.daily_limit_minutes} min/day</p>)}</section>}
 <footer>Screen Time Control · Logged moments, clearer days.</footer></main></div>;
}
